media_namespace: media-server

sonarr_repo_url: https://charts.pree.dev

name_pv_config: config-media
capacity_pv_config: 30
path_config: /data

name_pv_data: data-media
capacity_pv_data: 30
path_data: /data

name_pvc_config: config-media-pvc


name_pvc_data: data-media-pvc
