all:
  vars:
    ansible_ssh_user: cloud
    ansible_ssh_private_key_file: /home/cloud/k3s_dedicated/NKO-KEY-BITWARDEN.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    k3s:
      hosts:
        k3s-test-nko:
          ansible_host: 90.84.45.251