- name: Deploy Values charts
  ansible.builtin.template:
    src: templates/flaresolverr_deployment.yaml.j2
    dest: /tmp/flaresolverr_deployment.yaml
    owner: "{{ kub_user }}"
    group: "{{ kub_group }}"
  tags:
    - flaresolverr_install

- name: Create a deployment
  kubernetes.core.k8s:
    apply: true
    state: present
    namespace: "{{ media_namespace }}"
    src: "/tmp/flaresolverr_deployment.yaml"
  tags:
    - flaresolverr_install
