- name: Deploy Values charts
  ansible.builtin.template:
    src: templates/radarr_deployment.yaml.j2
    dest: /tmp/radarr_deployment.yaml
    owner: "{{ kub_user }}"
    group: "{{ kub_group }}"
  tags:
    - radarr_install

- name: Create a deployment
  kubernetes.core.k8s:
    apply: true
    state: present
    namespace: "{{ media_namespace }}"
    src: "/tmp/radarr_deployment.yaml"
  tags:
    - radarr_install
