- name: Add sonarr repo
  kubernetes.core.helm_repository:
    name: pree-helm-charts  
    repo_url: "{{ sonarr_repo_url }}"

- name: Install Sonarr Chart
  kubernetes.core.helm:
    name: sonarr
    namespace: "{{ media_namespace }}"
    chart_ref: pree-helm-charts/sonarr

- name: Deploy Sonarr Chart
  kubernetes.core.helm:
    name: sonarr
    namespace: "{{ media_namespace }}"
    chart_ref: pree-helm-charts/sonarr
    values: "{{ lookup('template', 'sonarr_values.yaml') | from_yaml }}"