- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  tags:
    - packages

- name: Download k3s installer
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/install_k3s.sh
    mode: 'u+rwx'
  tags:
    - k3s
- name: exec the k3s installer
  ansible.builtin.shell: 
    cmd: "sh /tmp/install_k3s.sh >> install_k3s_{{ ansible_date_time.iso8601_basic_short }}.log"
  tags:
    - k3s

- name: Start service k3s, if not started
  ansible.builtin.service:
    name: k3s.service
    state: started
    enabled: yes
  tags:
    - k3s

- name: Insert yum repo for kube
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
  tags:
    - repository

- name: Get latest release kubectl bin
  shell:
    cmd: 'curl -o /root/kubectl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"'
  register: kubectl_file
  tags:
    - kub_conf

- name: Copy kubectl file
  copy:
    src: ~/kubectl
    dest: /usr/bin/kubectl
    mode: a+x
    owner: root
    group: root
    remote_src: yes
  tags:
    - kub_conf

- name: Create Directory for kub conf
  file:
    path: ~/.kube
    state: directory
  tags:
    - kub_conf
    - kub_file

- name: Copy k3s conf file
  shell:
    cmd: '\cp -r /etc/rancher/k3s/k3s.yaml ~/.kube/config'

  tags:
    - kub_conf
    - kub_file

