- name: Create Directory for {{ app_name }}
  ansible.builtin.file:
    path: "{{ path_config }}/config/{{ app_name }}/"
    state: directory
    owner: "{{ kub_user }}"
    group: "{{ kub_group }}"
  tags:
    - prowlarr_deployment

- name: Create config file for {{ app_name }}
  ansible.builtin.template:
    src: templates/prowlarr_conf.xml.j2
    dest: "{{ path_config }}/config/{{ app_name }}/config.xml"
    owner: "{{ kub_user }}"
    group: "{{ kub_group }}"
  tags:
    - prowlarr_deployment

- name: Deploy Values charts
  ansible.builtin.template:
    src: templates/{{ item }}
    dest: /tmp/{{ item | basename | regex_replace('\.j2$', '') }}
    owner: "{{ kub_user }}"
    group: "{{ kub_group }}"
  loop:
    - prowlarr_deployment.yaml.j2
    - prowlarr_body_DownloadClients.j2
    - prowlarr_app_radarr.j2
  tags:
    - prowlarr_install

- name: Create a deployment
  kubernetes.core.k8s:
    apply: true
    state: present
    namespace: "{{ media_namespace }}"
    src: "/tmp/prowlarr_deployment.yaml"
  tags:
    - prowlarr_install

- name: Wait for {{ app_name }} API access
  ansible.builtin.uri:
    url: "https://{{ web_name }}.{{ domain_name }}/api/v1/downloadclient?apikey={{ prowlarr_api_key }}"
    return_content: True
    timeout: 2
    validate_certs: "{{ validate_certs }}"
  register: prowlarr_url
  until: prowlarr_url['status']|default(0) == 200
  retries: 40
  delay: 3
  tags:
    - prowlarr_install

- name: Check {{ app_name }} configuration for Torrent client
  ansible.builtin.uri:
    url: https://{{ web_name }}.{{ domain_name }}/api/v1/downloadclient?apikey={{ prowlarr_api_key }}
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
  register: is_client_exist
  tags:
    - api

- name: Get body file
  ansible.builtin.slurp:
    src: "/tmp/prowlarr_body_DownloadClients"
  register: body_json
  when: is_client_exist.json|length < 1
  tags:
    - api

- name: Create Transmission Configuration
  ansible.builtin.uri:
    url: https://{{ web_name }}.{{ domain_name }}/api/v1/downloadclient?apikey={{ prowlarr_api_key }}
    method: POST
    body_format: json
    status_code: [200, 202, 201]
    return_content: true
    validate_certs: "{{ validate_certs }}"
    headers:
      Content-Type: application/json
      User-Agent: PostmanRuntime/7.29.2
      Accept-Encoding: gzip, deflate, br
    body: "{{ body_json['content'] | b64decode }}"
  when: is_client_exist.json|length < 1
  tags:
    - api

- name: Get App Radarr conf file
  ansible.builtin.slurp:
    src: "/tmp/prowlarr_app_radarr"
  register: app_sonar_json
  tags:
    - api

- name: Create APPLICATION RADARR Configuration
  ansible.builtin.uri:
    url: https://{{ web_name }}.{{ domain_name }}/api/v1/applications?apikey={{ prowlarr_api_key }}
    method: POST
    body_format: json
    status_code: [200, 202, 201]
    return_content: true
    validate_certs: "{{ validate_certs }}"
    headers:
      Content-Type: application/json
      User-Agent: PostmanRuntime/7.29.2
      Accept-Encoding: gzip, deflate, br
    body: "{{ app_sonar_json['content'] | b64decode }}"
  tags:
    - api