- name: Create k8s auth namespace
  kubernetes.core.k8s:
    name: "{{ auth_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  tags:
    - namespace

- name: Deploy Values charts
  ansible.builtin.template:
    src: "templates/{{ item }}"
    dest: /tmp/{{ item | basename | regex_replace('\.j2$', '') }}
    owner: "{{ kub_user }}"
    group: "{{ kub_group }}"
  loop:
    - "{{ app_name }}_deployment.yaml.j2"
    - "pv_config.yaml.j2"
    - "pvc_config.yaml.j2"
  tags:
    - app_install

- name: Create a deployment
  kubernetes.core.k8s:
    apply: true
    state: present
    namespace: "{{ auth_namespace }}" 
    src: /tmp/{{ item | basename | regex_replace('\.j2$', '') }}
  tags:
    - app_install
  loop:
    - "pv_config.yaml.j2"
    - "pvc_config.yaml.j2"
    - "{{ app_name }}_deployment.yaml.j2"

- name: Pause for Authelia pod
  ansible.builtin.pause:
    seconds: 5

- name: Copy file for Authelia Deployment
  ansible.builtin.template:
    src: "templates/{{ item }}"
    dest: /data/config/{{ app_name }}/{{ item | basename | regex_replace('\.j2$', '') }}
    owner: "{{ kub_user }}"
    group: "{{ kub_group }}"
  loop:
    - configuration.yml.j2
    - users_database.yml.j2

- name: kill {{ app_name }} pod
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Pod
    namespace: "{{ auth_namespace }}"
    label_selectors:
      - "app = {{ app_name }}"




