- name: Deploy Values charts
  ansible.builtin.template:
    src: templates/sonarr_deployment.yaml.j2
    dest: /tmp/sonarr_deployment.yaml
    owner: "{{ kub_user }}"
    group: "{{ kub_group }}"
  tags:
    - sonarr_install

- name: Create a deployment
  kubernetes.core.k8s:
    apply: true
    state: present            # State=present when you need to create new object
    namespace: "{{ media_namespace }}" # defining the namespace
    src: "/tmp/sonarr_deployment.yaml"
  tags:
    - sonarr_install