- name: Create k8s auth namespace
  kubernetes.core.k8s:
    name: "{{ passwords_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  tags:
    - namespace

- name: Deploy Values charts
  ansible.builtin.template:
    src: "templates/{{ item }}"
    dest: /tmp/{{ item | basename | regex_replace('\.j2$', '') }}
    owner: "{{ kub_user }}"
    group: "{{ kub_group }}"
  loop:
    - "{{ app_name }}_deployment.yaml.j2"
    - "password_pv_config.yaml.j2"
    - "password_pvc_config.yaml.j2"
  tags:
    - app_install

- name: Create a deployment
  kubernetes.core.k8s:
    apply: true
    state: present
    namespace: "{{ passwords_namespace }}" 
    src: /tmp/{{ item | basename | regex_replace('\.j2$', '') }}
  tags:
    - app_install
  loop:
    - "{{ app_name }}_deployment.yaml.j2"
    - "password_pv_config.yaml.j2"
    - "password_pvc_config.yaml.j2"

- name: Pause for Bitwarden pod
  ansible.builtin.pause:
    seconds: 5
